### PR TITLE
Second fix for RESPONSE_HEADERS

### PR DESCRIPTION
**Pull request by azurit**
Sorry guys, didn't noticed this :(

### CODE REVIEW

**Comment by azurit** [comment]
Providing more info for easier review:
With PL https://github.com/coreruleset/secrules_parsing/pull/8 i added `RESPONSE_HEADERS` into `CollectionName` but i forgot remove it from `Variable` - this PL is fixing this.

**Comment by airween** [comment]
Ah, thanks for clarification - now I think I understand the terminology: a token is a `Collection` member if it has a "sub-part" (eg, `RESPONSE_HEADER:Content-Type`), otherwise it's `Variable`?

If yes, it's a good catch too :) - LGTM.

**Comment by azurit** [comment]
> Ah, thanks for clarification - now I think I understand the terminology: a token is a `Collection` member if it has a "sub-part" (eg, `RESPONSE_HEADER:Content-Type`), otherwise it's `Variable`?

As far as i understand it, yes. :)

**Comment by azurit** [comment]
@fgsch ? @fzipi ?

**Comment by fzipi** [comment]
Collections are well defined in the reference manual, and match with what you are saying.
"Contains a collection of original file names (as they were called on the remote user’s filesys- tem). Available only on inspected multipart/form-data requests. "

LGTM.

**Comment by azurit** [comment]
Can be merged?

**Comment by azurit** [comment]
Thank you!

**Comment by airween** [comment]
> Collections are well defined in the reference manual, and match with what you are saying.

thanks,

> "Contains a collection of original file names (as they were called on the remote user’s filesys- tem). Available only on inspected multipart/form-data requests. "

btw I think this quoted text related to `FILES` collection. Based on the [reference](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#response_headers), the `RESPONSE_HEADER` is a "variable":
_"This variable may not have access to some headers..."_

But from the viewpoint from the parser, the behavior is clear :).

**Pull request merged**
