### PR TITLE
Support for SecRuleScript

### PR DESCRIPTION
**Pull request by azurit**
Adding support for `SecRuleScript`, please review closely!

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#SecRuleScript

### CODE REVIEW

**Comment by fzipi** [comment]
Question: did you tested it? I had problems in the past because in textX the directives order is important. In this case, it might give an error saying that it can't match SecRule, when the first SecRuleScript appears. I think that for this to work you need to add the longer match first.

**Comment by azurit** [comment]
No because i don't know how. Can you hint me with it?

**Comment by airween** [comment]
> No because i don't know how. Can you hint me with it?

See the [documentation](https://github.com/coreruleset/secrules_parsing#how-to-use-it-cli):

`python secrules_parser.py -f /owasp-crs/rules/*.conf`

(if you thought this one)

**Comment by azurit** [comment]
Ok, thank you, i fixed it. Anyway, if i try to run it locally, it prints `Syntax OK` no matter if `SecRuleScript` is before or after `SecRule`.

**Comment by airween** [comment]
> Anyway, if i try to run it locally, it prints `Syntax OK` no matter if `SecRuleScript` is before or after `SecRule`.

well, you're right - it works for me too. It's interesting, but IMHO it's better if you follow the convention (as you fixed).

Thanks.

**Comment by fzipi** [comment]
Excellent. Sadly I can't test it myself, as I'm away from my laptop from the next week or so.

LGTM.

Just in case, the parser was created as basically just to be useful for the crs, that's why it doesn't have all modsec directives (yet).

**Pull request merged**
