### PR TITLE
Macro support to Tag

### PR DESCRIPTION
**Pull request by azurit**
Rule tags supports macro expansion.

### CODE REVIEW

**Comment by azurit** [comment]
@fzipi can you be so kind and look at this? Thank you.

**Comment by fgsch** [comment]
Do you have an example of this you can share? Thank you.

**Comment by azurit** [comment]
See https://github.com/coreruleset/coreruleset/issues/1979.

**Comment by azurit** [comment]
Closing, as macro support in tags is going to be removed in modsecurity 3.1.

**Pull request closed without merging**
