### PR TITLE
Allow whitespace and single quotes (') in values after @contains

### PR DESCRIPTION
**Pull request by azurit**
Fix for failing test in PL https://github.com/coreruleset/coreruleset/pull/1962: Allow whitespace and single quotes (') in values after @contains.

### CODE REVIEW

**Comment by airween** [comment]
That PR contains a `'` [here](https://github.com/coreruleset/coreruleset/pull/1962/files#diff-90cc6d344f17b55d37a948db942ac62a15179e58efe51d66c82d7801cba0b69bR115).

Wouldn't be that a problem too?

**Comment by azurit** [comment]
> That PR contains a `'` [here](https://github.com/coreruleset/coreruleset/pull/1962/files#diff-90cc6d344f17b55d37a948db942ac62a15179e58efe51d66c82d7801cba0b69bR115).
> 
> Wouldn't be that a problem too?

Good catch! Thank you.

Anyway, i think we should not use `PathNameValue` for `@contains`.

**Comment by airween** [comment]
> Anyway, i think we should not use `PathNameValue` for `@contains`.

Yes, perhaps.

Here is the part of the BNF syntax:

Operator -> ... ['contains' contains=PathOrMacro](https://github.com/coreruleset/secrules_parsing/blob/master/secrules.tx#L68) ...

PathOrMacro -> [PathNameValue | MacroVar](https://github.com/coreruleset/secrules_parsing/blob/master/secrules.tx#L123);

PathNameValue -> [/[a-z0-9\-_\.\/]+/](https://github.com/coreruleset/secrules_parsing/blob/master/secrules.tx#L126);

MacroVar -> ['%{'? /[a-zA-Z0-9-\_\.]+/ '}'?](https://github.com/coreruleset/secrules_parsing/blob/master/secrules.tx#L136);

So, I should add the spec characters to `MacroVar` rather than `PathNameValue`.

And IMHO macros can contain so many special characters, eg. `%`, `#`, `&`, `\`, `=` ... so added these chars can help to avoid the similar bugs like in modsecurity3 (2145 and 3238). But ask @fzipi and/or @fgsch :).

**Comment by azurit** [comment]
`MacroVar` must start with a `%`, musn't it? But maybe i'm misunderstanding the syntax, i'm not very skilled with `textX`.

`MacroVar: '%{'? /[a-zA-Z0-9-\_\.]+/ '}'?;`

**Comment by airween** [comment]
> `MacroVar` must start with a `%`, musn't it? But maybe i'm misunderstanding the syntax, i'm not very skilled with `textX`.

yes, it must - you're right. And I'm not sure that macro can contains any characters I listed. Then we should extend the syntax with a new terminal symbol near to `MacroVar` and `PathNameValue`.

**Comment by airween** [comment]
I think this patch solves the problem in your mentioned issue (use the existing `ExtendedMacro` after `@contains`):

```diff
--- a/secrules.tx
+++ b/secrules.tx
@@ -65,7 +65,7 @@ Count: '&';
 
 //- pattern match (pm/pmf)    
 Operator:
-    ('beginsWith' beginswith=PathOrMacro | 'contains' contains=PathOrMacro | 'containsWord' containsWord=STRING | detectsqli ?= 'detectSQLi' | detectxss ?= 'detectXSS' | 'endsWith' endswith=ExtendedMacro | 'fuzzyHash' fuzzyhash=STRING | 'eq' eq=INT | 'ge' ge=Macro | geolookup ?= 'geoLookup'  | 'gsbLookup' gsblookup=INT | 'gt' gt=Macro | 'inspectFile' inspectfile=URI | 'ipMatch' ipmatch+=IPCIDR[','] |'ipMatchF' ipmatchf=STRING | 'ipMatchFromFile' ipmatchfromfile=STRING | 'le' le=INT | 'lt' lt=Macro | nomatch ?= 'noMatch' | 'pmf' pmf=PathNameValue | 'pmFromFile' pmfromfile=PathNameValue | 'pm' pm=PatternMatch | 'rbl' rbl=Hostname | 'rsub' rsub=AnythingBetweenSlashes | 'rx' rx=RegExp | 'streq' streq=StringWithSpaces | 'strmatch' strnmatch=STRING | unconditionalmatch ?= 'unconditionalMatch' | 'validateByteRange' validatebyterange=ByteRangeList | 'validateDTD' validatedtd=PathNameValue | 'validateHash' validatehash=RegExp | 'validateSchema' validateschema=PathNameValue | validateurlencoding ?= 'validateUrlEncoding' | validateutf8encoding ?= 'validateUtf8Encoding' | 'verifyCC' verifycc=RegExp | 'verifyCPF' verifycpf=STRING | 'verifySSN' verifyssn=RegExp | 'within' within=MacroOrString | '' rx=RegExp);
+    ('beginsWith' beginswith=PathOrMacro | 'contains' contains=ExtendedMacro | 'containsWord' containsWord=STRING | detectsqli ?= 'detectSQLi' | detectxss ?= 'detectXSS' | 'endsWith' endswith=ExtendedMacro | 'fuzzyHash' fuzzyhash=STRING | 'eq' eq=INT | 'ge' ge=Macro | geolookup ?= 'geoLookup'  | 'gsbLookup' gsblookup=INT | 'gt' gt=Macro | 'inspectFile' inspectfile=URI | 'ipMatch' ipmatch+=IPCIDR[','] |'ipMatchF' ipmatchf=STRING | 'ipMatchFromFile' ipmatchfromfile=STRING | 'le' le=INT | 'lt' lt=Macro | nomatch ?= 'noMatch' | 'pmf' pmf=PathNameValue | 'pmFromFile' pmfromfile=PathNameValue | 'pm' pm=PatternMatch | 'rbl' rbl=Hostname | 'rsub' rsub=AnythingBetweenSlashes | 'rx' rx=RegExp | 'streq' streq=StringWithSpaces | 'strmatch' strnmatch=STRING | unconditionalmatch ?= 'unconditionalMatch' | 'validateByteRange' validatebyterange=ByteRangeList | 'validateDTD' validatedtd=PathNameValue | 'validateHash' validatehash=RegExp | 'validateSchema' validateschema=PathNameValue | validateurlencoding ?= 'validateUrlEncoding' | validateutf8encoding ?= 'validateUtf8Encoding' | 'verifyCC' verifycc=RegExp | 'verifyCPF' verifycpf=STRING | 'verifySSN' verifyssn=RegExp | 'within' within=MacroOrString | '' rx=RegExp);
 
 /* Actions are separated by ',\' or ',' only */
 //ActionList: actionlist+=;
```

I can make a new PR - if you think this is a better solution, close this issue and I'll open a new one.

**Comment by azurit** [comment]
I think this is better solution but pls also add single quotes (') to the `ExtendedMacro`, it's missing it. Thank you.

**Pull request closed without merging**
